### ISSUE TITLE
make clean deletes openj9_version_info.h

### ISSUE THREAD

**Issue by pdbain** [ibmruntimes/openj9-openjdk-jdk9#11]
This file is created during the configure step.  make clean deletes the file, so "make clean; make all" fails due to the missing file.

**Comment by davew16** [comment]
The openj9_version_info.h file is created in the $OUTPUT_ROOT/vm/util by the configure script.  Autoconf is used to create the file with the required contents.  This step is configured near the bottom of closed/autoconf/custom-hook.m4, and when the configure script is run the task of creating the openj9_version_info.h file is added to closed/autoconf/generated-configure.sh.

($OUTPUT_ROOT is build/linux-x86_64-normal-server-release in my Ubuntu machine)

Unfortunately the $OUTPUT_ROOT/vm directory is volatile, and is deleted when running _make clean_, so a subsequent make all will fail because the openj9_version_info.h file does not exist.

The simple workaround is to re-run the configure script after doing a _make clean_.

The proper fix should be to either:
- have the configure script create the openj9_version_info.h file in a non-volatile directory, the directory needs to be in the include path for the native compiler or the directory will need to be added to the native compiler's include path, or even better...
- have _make_ create the openj9_version_info.h file instead of configure.  During _make all_ the jdk/make/gensrc/GensrcMisc.gmk file creates the $(SUPPORT_OUTPUTDIR)/gensrc/java.base/java/lang/VersionProps.java file with the required contents in a similar manner to the way the configure script creates the openj9_version_info.h file.  Perhaps a similar mechanism could be used to fix this issue.

**Comment by keithc-ca** [comment]
@ben-walsh I hope I haven't stepped on your toes. I only noticed your commit after I had my solution working.
