### ISSUE TITLE
Copyright dates not updated in #109

### ISSUE THREAD

**Issue by pshipton** [ibmruntimes/openj9-openjdk-jdk9#113]
@adamfarley https://github.com/ibmruntimes/openj9-openjdk-jdk9/pull/109 merged a couple of files without updating the copyright end dates. Please do so. Same with https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/32

There should be a copyright check running now on pull requests to indicate when copyright dates are incorrect. Please check it before merging. In general a failure indicates that copyrights need to be updated, although in some cases such as when removing all OpenJ9 changes and reverting to the original OpenJDK revistion, the copyright check can be ignored.

@lumpfish @ben-walsh @andrew-m-leonard fyi

**Comment by adamfarley** [comment]
Addendum: Peter and Adam B have (as per https://github.com/ibmruntimes/openj9-openjdk-jdk9/issues/114) since discovered that the copyright-checks were not launched in #109, so there was nothing to check before merging.

I acknowledge the lapse though, as I should have checked it manually, and I still plan to fix the copyrights.

**Comment by adamfarley** [comment]
Fixed, finally. :)
