### ISSUE TITLE
Merge check details not available

### ISSUE THREAD

**Issue by pshipton** [ibmruntimes/openj9-openjdk-jdk9#114]
@AdamBrousseau in an OpenJ9 PR after merge there is a "View Details" button to see the status of the merge checks. Can this be enabled on the jdk8 & 9 repos?

**Comment by AdamBrousseau** [comment]
If there are no checks performed then there is nothing to show. I am unsure why #109 and #110 didn't get any builds. I think the behaviour is correct, the issue is with the builds not launching.
https://ci.eclipse.org/openj9/view/Pull%20Requests/job/PullRequest-LineEndingsCheck-OpenJ9-OpenJDK-JDK9/
https://ci.eclipse.org/openj9/view/Pull%20Requests/job/PullRequest-CopyrightCheck-OpenJ9-OpenJDK-JDK9/
