### ISSUE TITLE
document how to map a directory to the docker container?

### ISSUE THREAD

**Issue by davew16** [ibmruntimes/openj9-openjdk-jdk9#12]
This suggestion assumes that there will be people who want to build the openj9-openjdk-jdk9 binaries themselves, but they are not already familiar with docker.

If such people exist they will follow the instructions in the OpenJ9 Build README and successfully build the OpenJ9 binaries in the docker container.  However, the instructions don't include mapping a host directory into the docker container, so they won't be able to copy the binaries into a more permanent location.

I suggest changing the README file as follows:
- change the "docker run -it openj9" instruction to something like "docker run -v <target_directory_path>:/root/hostdir -it openj9"
- after all the instructions to perform the build and run ./bin/java -version, add an instruction to copy the binaries to /root/hostdir so that they will still exist after you exit the docker container.

**Comment by mstoodle** [comment]
Thanks for opening the issue @davew16 . Can I ask you to open this issue at our website repository at https://github.com/eclipse/openj9-website ?

I'll put a small response here: we were trying to keep those initial instructions as simple as possible, but we don't have the more comprehensive directions page backing it up yet, which is where I think your suggestion makes a lot of sense. Once the issue is opened at the website repo, we'll close this one.

**Comment by davew16** [comment]
I have created a new issue at https://github.com/eclipse/openj9-website as suggested ([here](https://github.com/eclipse/openj9-website/issues/13)).  Closing this issue now.
