### ISSUE TITLE
Create extensions for Java 18.3

### ISSUE THREAD

**Issue by pshipton** [ibmruntimes/openj9-openjdk-jdk9#38]
In order to create an OpenJ9 build for Java 18.3, a new extensions project is needed to extend http://hg.openjdk.java.net/jdk10/master

**Comment by Bluevisitor** [comment]
I'm working on a local copy of Extensions for Openjdk10 for Eclipse OpenJ9. Openjdk10 is patched, and passes the configure step, but fails during the build. I'm working on it now, and I'll update once the build passes.

**Comment by pshipton** [comment]
Note the link I provided originally is out of date, and should be http://hg.openjdk.java.net/jdk10/master. I've edited to the original comment to update the link.

**Comment by mstoodle** [comment]
@adamfarley just curious how are you removing Hotspot from your Extensions repo, given the new consolidated forest?

**Comment by adamfarley** [comment]
@mstoodle - I'm not. I made the initial "copy" of OpenJDK10 before the jdk10 forest was consolidated, and the work has since been deprioritised. I understand @davew16 is working with the consolidated forest at the moment, but right now we have no solution for the Hotspot removal, nor do we have a concrete plan in place.

**Comment by mstoodle** [comment]
ok, that explains it :) .

Maybe we'll need to do something like what's described here: https://stackoverflow.com/questions/10067848/remove-folder-and-its-contents-from-git-githubs-history

And then somehow keep it going as we pull new things into the master branch ?
