### ISSUE TITLE
make test fails

### ISSUE THREAD

**Issue by JamesKingdon** [ibmruntimes/openj9-openjdk-jdk9#96]
Is the test subdirectory maintained? The documentation links for testing all seem to lead to out of project material that doesn't involve the test directory, and I don't see anything in-project that talks about it. Running ```make test``` in the openj9-openjdk-jdk9 directory (after a successful ```make all```) appears to attempt to enter the test directory, but quickly fails:
```
make[3]: 8: Command not found
echo "Running tests: jdk_core"
Running tests: jdk_core
for each in jdk_core; do \
        /usr/bin/make -j 1 TEST_SELECTION=":$each" UNIQUE_DIR=$each jtreg_tests; \
done
make[5]: *** No rule to make target '/java/re/jtreg/4.2/promoted/latest/binaries/jtreg', needed by 'jtreg_exists'.
make[5]: Target 'jtreg_tests' not remade because of errors.
```

**Comment by jdekonin** [comment]
I am uncertain anyone has spent effort with investigating errors in the openjdk/test material.  Although I think the error that you are getting here is because there is an addition jtreg harness download that needs to be performed.

That aside, for running testing that will be specific to the the openj9 implementation these instructions should work.  https://github.com/eclipse/openj9/blob/master/test/README.md

There will likely be tests specific to the hotspot 'component' that with the openj9 extensions are purposefully omitted.  You can more than welcome to attempt and raise issues though!

https://github.com/ibmruntimes/openj9-openjdk-jdk9/blob/openj9/common/doc/testing.md
same doc but in the host repo...
http://hg.openjdk.java.net/jdk9/jdk9/file/a08cbfc0e4ec/common/doc/testing.md

**Comment by JamesKingdon** [comment]
Many thanks for the info. I'll start with the openj9 specifics and then circle back to the openjdk material and see if I can get anything working.

**Comment by JamesKingdon** [comment]
OK, I think this issue just reflected a lack of understanding on my part. I'll close it.

Testing for OpenJ9: https://github.com/eclipse/openj9/blob/master/test/README.md
Testing for OpenJDK: https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/README.md
